<?xml version="1.0" encoding="UTF-8"?>
<svg width="16px" height="16px" viewBox="0 0 16 16" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 40.3 (33839) - http://www.bohemiancoding.com/sketch -->
    <title>makefile</title>
    <desc>Created with Sketch.</desc>
    <defs>
        <rect id="path-1" x="5" y="0" width="2" height="12"></rect>
        <mask id="mask-2" maskContentUnits="userSpaceOnUse" maskUnits="objectBoundingBox" x="0" y="0" width="2" height="12" fill="white">
            <use xlink:href="#path-1"></use>
        </mask>
        <rect id="path-3" x="5" y="0" width="2" height="12"></rect>
        <mask id="mask-4" maskContentUnits="userSpaceOnUse" maskUnits="objectBoundingBox" x="0" y="0" width="2" height="12" fill="white">
            <use xlink:href="#path-3"></use>
        </mask>
        <rect id="path-5" x="5" y="0" width="2" height="12"></rect>
        <mask id="mask-6" maskContentUnits="userSpaceOnUse" maskUnits="objectBoundingBox" x="0" y="0" width="2" height="12" fill="white">
            <use xlink:href="#path-5"></use>
        </mask>
        <rect id="path-7" x="5" y="0" width="2" height="12"></rect>
        <mask id="mask-8" maskContentUnits="userSpaceOnUse" maskUnits="objectBoundingBox" x="0" y="0" width="2" height="12" fill="white">
            <use xlink:href="#path-7"></use>
        </mask>
        <circle id="path-9" cx="6" cy="6" r="4"></circle>
        <mask id="mask-10" maskContentUnits="userSpaceOnUse" maskUnits="objectBoundingBox" x="0" y="0" width="8" height="8" fill="white">
            <use xlink:href="#path-9"></use>
        </mask>
    </defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="makefile" stroke="#979797" fill="#D8D8D8">
            <g id="Group" transform="translate(2.000000, 2.000000)">
                <use id="Rectangle" mask="url(#mask-2)" stroke-width="2" xlink:href="#path-1"></use>
                <use id="Rectangle" mask="url(#mask-4)" stroke-width="2" transform="translate(6.000000, 6.000000) rotate(-315.000000) translate(-6.000000, -6.000000) " xlink:href="#path-3"></use>
                <use id="Rectangle" mask="url(#mask-6)" stroke-width="2" transform="translate(6.000000, 6.000000) rotate(-270.000000) translate(-6.000000, -6.000000) " xlink:href="#path-5"></use>
                <use id="Rectangle" mask="url(#mask-8)" stroke-width="2" transform="translate(6.000000, 6.000000) rotate(-225.000000) translate(-6.000000, -6.000000) " xlink:href="#path-7"></use>
                <use id="Oval-3" mask="url(#mask-10)" stroke-width="4" xlink:href="#path-9"></use>
            </g>
        </g>
    </g>
</svg>